const data = [
    {
        id:50021,
        name:"طرح درس روزانه فصل 2 کسر ریاضی",
        caption:"طرح درس فصل 2 کسر ریاضی — پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"WORD",
        src:"/Files/panjom/tarhedars/طرح-درس-فصل-2-کسر-ریاضی-(سری1)-پنجم-دبستان.docx",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50021"
    } , 
    {
        id:50022,
        name:"طرح درس سالانه ریاضی پنجم ابتدایی",
        caption:"طرح درس سالانه ریاضی پنجم ابتدایی - پایه پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"WORD",
        src:"/Files/panjom/tarhedars/طرح درس سالانه ریاضی پنجم ابتدایی.doc",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50022"
    } ,
    {
        id:50023,
        name:"طرح درس سالانه بخوانیم پنجم ابتدایی",
        caption:"طرح درس سالانه بخوانیم پنجم ابتدایی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"WORD",
        src:"/Files/panjom/tarhedars/طرح درس سالانه بخوانیم پنجم ابتدایی.doc",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/tarhedars/50023"
    } , 
    {
        id:50024,
        name:"طرح درس روزانه جمعیت ایران مطالعات اجتماعی",
        caption:"طرح درس جمعیت ایران مطالعات اجتماعی پنجم ابتدایی",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"WORD",
        src:"/Files/panjom/tarhedars/طرح درس جمعیت ایران مطالعات اجتماعی پنجم ابتدایی.doc",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/tarhedars/50024"
    } , 
    {
        id:50025,
        name:"طرح درس روزانه درس نهم فارسی پنجم",
        caption:"طرح درس روزانه درس نهم فارسی - پایه پنجم",
        creator:"خانم ندا باقریان",
        upoledDate:"1403/09/09",
        fileType:"PDF",
        src:"https://coding-lbf.storage.iran.liara.space/1_12097924154.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/tarhedars/50025"
    }, 
    {
        id:50026,
        name:"طرح درس روزانه ضرب عدد مخلوط",
        caption:"طرح درس روزانه ضرب عدد مخلوط - پایه پنجم",
        creator:"سلمان نوری",
        upoledDate:"1403/09/29",
        fileType:"PDF",
        src:"https://coding-lbf.storage.iran.liara.space/sheshom/nouri/01/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%202.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50026"
    },     {
        id:50027,
        name:"طرح درس روزانه ضرب عدد مخلوط - شماره 2",
        caption:"طرح درس روزانه ضرب عدد مخلوط - شماره 2 - پایه پنجم",
        creator:"سلمان نوری",
        upoledDate:"1403/09/29",
        fileType:"PDF",
        src:"https://coding-lbf.storage.iran.liara.space/sheshom/nouri/01/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D9%BE%D9%86%D8%AC%D9%85.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50027"
    },     {
        id:50028,
        name:"طرح درس روزانه تربیت بدنی پنجم",
        caption:"طرح درس روزانه تربیت بدنی - پایه پنجم",
        creator:"سلمان نوری",
        upoledDate:"1403/09/29",
        fileType:"PDF",
        src:"https://coding-lbf.storage.iran.liara.space/sheshom/nouri/01/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%AA%D8%B1%D8%A8%DB%8C%D8%AA%20%D8%A8%D8%AF%D9%86%DB%8C.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50028"
    }, 
    {
        id:50029,
        name:"طرح درس جمع و تفریق اعداد مرکب پایه پنجم",
        caption:"طرح درس جمع و تفریق اعداد مرکب - پایه پنجم",
        creator:"خانم ندا باقریان",
        upoledDate:"1403/10/23",
        fileType:"PDF",
        src:"https://coding-lbf.storage.iran.liara.space/panjom/bagherian/04/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%AC%D9%85%D8%B9%20%D9%88%20%D8%AA%D9%81%D8%B1%DB%8C%D9%82%20%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF%20%D9%85%D8%B1%DA%A9%D8%A8%20%D9%BE%D8%A7%DB%8C%D9%87%20%D9%BE%D9%86%D8%AC%D9%85.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/tarhedars/50029"
    },
        

]

export default data