import Head from "next/head";
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import Image from "next/image";
// import { Inter } from "next/font/google";
import HomePage from "@/components/templates/HomePage";
import DeveloperPage from "@/components/templates/DeveloperPage";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  
  useEffect(() => {
    const isAuthenticated = Cookies.get('auth');
    if (isAuthenticated !== 'true') {
      router.push('/login'); // هدایت به صفحه لاگین در صورت عدم احراز هویت
    }
  }, []);
  
  return (
    <>
      <Head>
        <title>سامانه همیار معلم دبستان شهید جهان آرا</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{minHeight:"100vh"}}>
        <DeveloperPage />
      </main>
    </>
  );
}
