const data = [
    {
        id:30011,
        name:"آزمون مستمر مهر ماه علوم سوم",
        caption:"آزمون مستمر علوم تجربی پایه سوم، از درس 1، مهر ماه",
        creator:"محمد لبافی",
        upoledDate:"1403/07/26",
        fileType:"PDF",
        src:"/Files/sevom/soalat/101.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/oloom.jpg",
        slug: "/sevom/soalat/30011"
    } , 
    {
        id:30012,
        name:"آزمونک ریاضی سوم ابتدائی | فصل 1: الگوها",
        caption:"آزمونک شامل 9 سوال در 2 صفحه، در سطح آسان ویژه ی ارزشیابی توصیفی با جدول عملکرد اهداف",
        creator:"محمد لبافی",
        upoledDate:"1403/08/15",
        fileType:"WORD",
        src:"/Files/sevom/soalat/102.docx",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30012"
    } ,
    {
        id:30013,
        name:"پرسش و پاسخ درس ۴-۵-۶ علوم سوم",
        caption:"سوالات پرسش و پاسخ درس ۴-۵-۶ علوم سوم به همراه جواب",
        creator:"محمد لبافی",
        upoledDate:"1403/08/15",
        fileType:"PDF",
        src:"/Files/sevom/soalat/103.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/oloom.jpg",
        slug: "/sevom/soalat/30013"
    } ,
    {
        id:30014,
        name:"تمرین جدول ضرب",
        caption:"تمرین جدول ضرب - ریاضی پایه سوم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/16",
        fileType:"PDF",
        src:"/Files/sevom/soalat/104.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30014"
    } ,
    {
        id:30015,
        name:"آزمون شماره 1 جدول ضرب",
        caption:"آزمون شماره 1 جدول ضرب - ریاضی پایه سوم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/16",
        fileType:"PDF",
        src:"/Files/sevom/soalat/105.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30015"
    } ,
    {
        id:30016,
        name:"آزمون شماره 2 جدول ضرب",
        caption:"آزمون شماره 2 جدول ضرب - ریاضی پایه سوم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/16",
        fileType:"PDF",
        src:"/Files/sevom/soalat/106.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30016"
    } ,
    
        {
            id:30017,
            name:"کلیه سوالات کتاب علوم سوم",
            caption:"کلیه سوالات کتاب علوم درس به درس با جواب",
            creator:"محمد لبافی",
            upoledDate:"1403/08/16",
            fileType:"PDF",
            src:"/Files/sevom/soalat/107.pdf",
            book:"oloom",
            boolInP:"علوم",
            gradeInP:"پایه سوم",
            image:"/images/components/modules/books/sevom/oloom.jpg",
            slug: "/sevom/soalat/30017"
        } ,
        {
            id:30018,
            name:"کاربرگ خلاق مخالف و هم خانواده درس سوم فارسی",
            caption:"کاربرگ خلاق مخالف و هم خانواده درس سوم فارسی - پایه سوم",
            creator:"محمد لبافی",
            upoledDate:"1403/08/16",
            fileType:"JPG",
            src:"/Files/sevom/soalat/108.jpeg",
            book:"farsi",
            boolInP:"فارسی",
            gradeInP:"پایه سوم",
            image:"/images/components/modules/books/sevom/farsi.jpg",
            slug: "/sevom/soalat/30018"
        } ,
        {
            id:30019,
            name:"کاربرگ خلاق مترادف درس سوم فارسی",
            caption:"کاربرگ خلاق مترادف درس سوم فارسی - پایه سوم",
            creator:"محمد لبافی",
            upoledDate:"1403/08/16",
            fileType:"JPG",
            src:"/Files/sevom/soalat/109.jpg",
            book:"farsi",
            boolInP:"فارسی",
            gradeInP:"پایه سوم",
            image:"/images/components/modules/books/sevom/farsi.jpg",
            slug: "/sevom/soalat/30019"
        } ,
        {
            id:30020,
            name:"5 سری نمونه سوال استاندارد آزمون نوبت اول مطالعات اجتماعی سوم",
            caption:"5 نمونه سوال امتحان ترم اول مطالعات اجتماعی شامل انواع سوالات + پاسخ تشریحی همه آزمون‌ها",
            creator:"محمد لبافی",
            upoledDate:"1403/08/16",
            fileType:"WORD",
            src:"/Files/sevom/soalat/110.docx",
            book:"motaleat",
            boolInP:"مطالعات اجتماعی",
            gradeInP:"پایه سوم",
            image:"/images/components/modules/books/sevom/motaleat.jpg",
            slug: "/sevom/soalat/30020"
        } ,        {
            id:30021,
            name:"آزمون عملکردی فصل 2 آموزش روخوانی قرآن کریم ",
            caption:"آزمون عملکردی فصل 2 آموزش روخوانی قرآن کریم — سوم دبستان",
            creator:"محمد لبافی",
            upoledDate:"1403/08/21",
            fileType:"PDF",
            src:"/Files/sevom/soalat/آزمون-عملکردی-فصل-2-آموزش-روخوانی-قرآن-کریم-قرآن-(سری1)-سوم-دبستان.pdf",
            book:"quran",
            boolInP:"آموزش قرآن",
            gradeInP:"پایه سوم",
            image:"/images/components/modules/books/sevom/quran.jpg",
            slug: "/sevom/soalat/30021"
        } 
         , {
        id:30022,
        name:"آزمون عملکردی فصل 1 آموزش نماز",
        caption:"آزمون عملکردی فصل 1 آموزش نماز - پایه سوم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/21",
        fileType:"PDF",
        src:"/Files/sevom/soalat/آزمون-عملکردی-فصل-1-آموزش-نماز-قرآن-(سری1)-سوم-دبستان.pdf",
        book:"quran",
        boolInP:"قرآن",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/quran.jpg",
        slug: "/sevom/soalat/30022"
    }          , {
        id:30023,
        name:"نمونه سوال بخوانیم و بنویسیم درس 5 بلدرچین و برزگر",
        caption:"نمونه سوال بخوانیم و بنویسیم درس 5 بلدرچین و برزگر فارسی - پایه سوم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/21",
        fileType:"PDF",
        src:"/Files/sevom/soalat/نمونه-سوال-بخوانیم-و-بنویسیم-درس-5-بلدرچین-و-برزگر-فارسی-(سری1)-سوم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/farsi.jpg",
        slug: "/sevom/soalat/30023"
    } 
    , {
        id:30024,
        name:"نمونه سوال درس 4 هدیه های آسمان با پاسخ ",
        caption:"نمونه سوال درس 4 هدیه های آسمان با پاسخ  - پایه سوم ابتدایی",
        creator:"محمد لبافی",
        upoledDate:"1403/08/21",
        fileType:"WORD",
        src:"https://biamoz.com/dl/3/Hedie/d4/%D9%86%D9%85%D9%88%D9%86%D9%87-%D8%B3%D9%88%D8%A7%D9%84-%D8%AF%D8%B1%D8%B3-4-%D9%87%D8%AF%DB%8C%D9%87-%D9%87%D8%A7%DB%8C-%D8%A2%D8%B3%D9%85%D8%A7%D9%86-%D8%A8%D8%A7-%D9%BE%D8%A7%D8%B3%D8%AE-%D8%B3%D9%88%D9%85-%D8%A7%D8%A8%D8%AA%D8%AF%D8%A7%DB%8C%DB%8C_Biamoz.com.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/hedye.jpg",
        slug: "/sevom/soalat/30024"
    }    , {
        id:30025,
        name:"ارزشیابی مستمر درس 1-2-3 هدیه های آسمان",
        caption:"ارزشیابی مستمر درس 1-2-3 هدیه های آسمان — سوم ابتدایی",
        creator:"محمد لبافی",
        upoledDate:"1403/08/21",
        fileType:"PDF",
        src:"https://biamoz.com/dl/3/Hedie/d3/%D8%A7%D8%B1%D8%B2%D8%B4%DB%8C%D8%A7%D8%A8%DB%8C-%D9%85%D8%B3%D8%AA%D9%85%D8%B1-%D8%AF%D8%B1%D8%B3-1-%D8%AA%D8%A7-3-%D9%87%D8%AF%DB%8C%D9%87-%D9%87%D8%A7%DB%8C-%D8%A2%D8%B3%D9%85%D8%A7%D9%86-%D8%B3%D9%88%D9%85-%D8%A7%D8%A8%D8%AA%D8%AF%D8%A7%DB%8C%DB%8C_Biamoz.com.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/hedye.jpg",
        slug: "/sevom/soalat/30025"
    } 
    , {
        id:30026,
        name:"ارزشیابی مستمر فصل یک ریاضی",
        caption:"نمونه سوالات ارزشیابی مستمر فصل یک ریاضی - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/25",
        fileType:"PDF",
        src:"/Files/sevom/soalat/فصل یک.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30026"
    } 
    , {
        id:30027,
        name:"نمونه سوالات تبدیل واحد - فصل دوم ریاضی",
        caption:"نمونه سوالات تبدیل واحد - فصل دوم ریاضی - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/25",
        fileType:"PDF",
        src:"/Files/sevom/soalat/فصل دوم-تبدیل واحد.pdf", 
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30027"
    }
    , {
        id:30028,
        name:"ارزشیابی مستمر فصل دوم ریاضی",
        caption:"ارزشیابی مستمر فصل دوم ریاضی - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/25",
        fileType:"PDF",
        src:"/Files/sevom/soalat/آزمون فصل دو.pdf", 
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30028"
    }  
    , {
        id:30029,
        name:"نمونه سوالات ارزش پول - فصل دوم ریاضی",
        caption:"نمونه سوالات ارزش پول - فصل دوم ریاضی  - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/25",
        fileType:"PDF",
        src:"/Files/sevom/soalat/فصل دوم-ارزش پول.pdf", 
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/riazi.jpg",
        slug: "/sevom/soalat/30029"
    } 
    , {
        id:30030,
        name:"نمونه سوالات ارزشیابی آبان ماه فارسی",
        caption: "نمونه سوالات ارزشیابی آبان ماه فارسی - پایه سوم",
        creator:"خانم حدیث مرادی پور",
        upoledDate:"1403/08/27",
        fileType:"PDF",
        src:"/Files/sevom/soalat/farsi-p3.pdf", 
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/farsi.jpg",
        slug: "/sevom/soalat/30030"
    }
    // {
    //     id:30031,
    //     name:"نمونه سوالات مرور فصل 1 و2 ریاضی",
    //     caption: "نمونه سوالات مرور فصل 1 و 2ریاضی - پایه سوم",
    //     creator:"خانم فاطمه امراللهی",
    //     upoledDate:"1403/08/30",
    //     fileType:"PDF",
    //     src:"/Files/sevom/soalat/فصل 1 و2.pdf", 
    //     book:"riazi",
    //     boolInP:"ریاضی",
    //     gradeInP:"پایه سوم",
    //     image:"/images/components/modules/books/sevom/riazi.jpg",
    //     slug: "/sevom/soalat/30031"
    // } 
    ,
    {
        id:30032,
        name:"آزمون مداد کاغذی درس اول ودوم فارسی",
        caption: "آزمون مداد کاغذی درس اول ودوم فارسی - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/30",
        fileType:"PDF",
        src:"/Files/sevom/soalat/1_14230795506.pdf", 
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/farsi.jpg",
        slug: "/sevom/soalat/30032"
    } 
    ,
    {
        id:30033,
        name:"نمونه سوالات درس 3 تا 5 فارسی",
        caption: "نمونه سوالات درس 3 تا 5 فارسی - پایه سوم",
        creator:"خانم فاطمه امراللهی",
        upoledDate:"1403/08/30",
        fileType:"PDF",
        src:"/Files/sevom/soalat/نمونه سوال درس 3 تا 5 فارسی.pdf", 
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/farsi.jpg",
        slug: "/sevom/soalat/30033"
    } 
    ,
    {
        id:30034,
        name:"نمونه سوال فصل 1 و 2 مطالعات اجتماعی",
        caption: "نمونه سوال فصل 1 و 2 مطالعات اجتماعی - پایه سوم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/30",
        fileType:"PDF",
        src:"/Files/sevom/soalat/نمونه-سوال-فصل-1-و-2-مطالعات-اجتماعی-سوم-ابتدایی.pdf", 
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه سوم",
        image:"/images/components/modules/books/sevom/motaleat.jpg",
        slug: "/sevom/soalat/30034"
    } 
    , 
    {
       id:40035,
       name:"مرور فصل 1 و 2 ریاضی",
       caption:"مرور فصل 1 و 2 ریاضی - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/09/16",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/%D9%85%D8%B1%D9%88%D8%B11%D9%882.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40035"
    }
    , 
    {
       id:40036,
       name:"ارزشیابی فصل اول ریاضی",
       caption:"ارزشیابی فصل اول ریاضی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/16",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/riazi%20p3%281%29.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40036"
    }, 
    {
       id:40037,
       name:"آزمون فصل اول ریاضی",
       caption:"آزمون فصل اول ریاضی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/riazi%20fasl%201.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40037"
    }, 
    {
       id:40038,
       name:"آزمون فصل دوم ریاضی",
       caption:"آزمون فصل دوم ریاضی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/riazi%20fasl%202.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40038"
    }, 
    {
       id:40039,
       name:"آزمون درس اول ودوم فارسی",
       caption:"آزمون درس اول ودوم فارسی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/farsi1-2.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40039"
    }, 
    {
       id:40040,
       name:"آزمون درس سوم،چهارم وپنجم فارسی",
       caption:"آزمون درس سوم،چهارم وپنجم فارسی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/farsi%20dovom%203%2C4%2C5.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40040"
    }, 
    {
       id:40041,
       name:"آزمون درس شش،هفت وهشت فارسی",
       caption:"آزمون درس شش،هفت وهشت فارسی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/farsi%206%2C7%2C8.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40041"
    }, 
    {
       id:40042,
       name:"نمونه سوال فصل سوم ریاضی",
       caption:"نمونه سوال فصل سوم ریاضی - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/%D8%B3%D9%88%D9%85.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40042"
    }, 
    {
       id:40043,
       name:"نمونه سوال درس 6 فارسی",
       caption:"نمونه سوال درس 6 فارسی - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%206-.pdf",
       book:"farsi",
       boolInP:"فارسی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/farsi.jpg",
       slug: "/sevom/soalat/40043"
    }, 
    {
       id:40044,
       name:"نمونه سوال درس هفتم فارسی",
       caption:"نمونه سوال درس هفتم فارسی - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%207.pdf",
       book:"farsi",
       boolInP:"فارسی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/farsi.jpg",
       slug: "/sevom/soalat/40044"
    }, 
    {
       id:40045,
       name:"نمونه سوال درس 8 فارسی",
       caption:"نمونه سوال درس 8 فارسی - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/09/22",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/8.pdf",
       book:"farsi",
       boolInP:"فارسی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/farsi.jpg",
       slug: "/sevom/soalat/40045"
    }, 
    {
       id:40047,
       name:"آزمون فارسی درس 1 تا 9",
       caption:"آزمون فارسی درس 1 تا 9 - پایه سوم",
       creator:"خانم فاطمه امراللهی",
       upoledDate:"1403/10/14",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/03/%D8%A2%D8%B2%D9%85%D9%88%D9%86%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%20%D8%AF%D8%B1%D8%B3%201%20%D8%AA%D8%A7%209.pdf",
       book:"farsi",
       boolInP:"فارسی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/farsi.jpg",
       slug: "/sevom/soalat/40047"
    }
    , 
    {
       id:40048,
       name:"آزمون درس ۹و۱۰ فارسی",
       caption:"آزمون درس ۹و۱۰ فارسی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/11/07",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/05/%D8%A2%D8%B2%D9%85%D9%88%D9%86%20%D8%AF%D8%B1%D8%B3%20%DB%B9%D9%88%DB%B1%DB%B0%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C.pdf",
       book:"farsi",
       boolInP:"فارسی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/farsi.jpg",
       slug: "/sevom/soalat/40048"
    }
    , 
    {
       id:40049,
       name:"آزمون فصل چهارم ریاضی",
       caption:"آزمون فصل چهارم ریاضی - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/11/07",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/05/%D8%A2%D8%B2%D9%85%D9%88%D9%86%20%D9%81%D8%B5%D9%84%20%DA%86%D9%87%D8%A7%D8%B1%D9%85%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40049"
    }
    , 
    {
       id:40050,
       name:"نمونه سوالات فصل دو ریاضی سوم",
       caption:"نمونه سوالات فصل دو ریاضی سوم - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/11/07",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/05/%D9%86%D9%85%D9%88%D9%86%D9%87%20%D8%B3%D9%88%D8%A7%D9%84%D8%A7%D8%AA%20%D9%81%D8%B5%D9%84%20%D8%AF%D9%88%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D8%B3%D9%88%D9%85.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40050"
    }
    , 
    {
       id:40051,
       name:"نمونه سوالات فصل سوم ریاضی سوم",
       caption:"نمونه سوالات فصل سوم ریاضی سوم - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/11/07",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/05/%D9%86%D9%85%D9%88%D9%86%D9%87%20%D8%B3%D9%88%D8%A7%D9%84%D8%A7%D8%AA%20%D9%81%D8%B5%D9%84%20%D8%B3%D9%88%D9%85%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D8%B3%D9%88%D9%85.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40051"
    }
    , 
    {
       id:40052,
       name:"نمونه سوالات فصل یک ریاضی سوم",
       caption:"نمونه سوالات فصل یک ریاضی سوم - پایه سوم",
       creator:"خانم حدیث مرادی پور",
       upoledDate:"1403/11/07",
       fileType:"PDF",
       src:"https://coding-lbf.storage.iran.liara.space/sevom/moradi/05/%D9%86%D9%85%D9%88%D9%86%D9%87%20%D8%B3%D9%88%D8%A7%D9%84%D8%A7%D8%AA%20%D9%81%D8%B5%D9%84%20%DB%8C%DA%A9%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D8%B3%D9%88%D9%85.pdf",
       book:"riazi",
       boolInP:"ریاضی",
       gradeInP:"پایه سوم",
       image:"/images/components/modules/books/sevom/riazi.jpg",
       slug: "/sevom/soalat/40052"
    },
    {
        "id": 49074,
        "name": "آزمون ریاضی فصل 1 تا 4",
        "caption": "آزمون ریاضی فصل 1 تا 4 - پایه سوم",
        "creator": "خانم فاطمه امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/1_17032521808.pdf",
        "book": "riazi",
        "boolInP": "ریاضی",
        "gradeInP": "پایه سوم",
        "category": "soalat",
        "image": "/images/components/modules/books/sevom/riazi.jpg",
        "slug": "/sevom/soalat/49074"
      },

   
   
]

export default data
