const data = [
    {
        id:50011,
        name:"نمونه سوال فصل 1 و 2 ریاضی با پاسخ",
        caption:"نمونه سوال فصل 1 و 2 ریاضی با پاسخ — پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-1-و-2-ریاضی-با-پاسخ-(سری1)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50011"
    } , 
    {
        id:50012,
        name:"نمونه سوال فصل 3 نسبت تناسب و درصد ریاضی",
        caption:"نمونه سوال فصل 3 نسبت تناسب و درصد ریاضی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-3-نسبت-تناسب-و-درصد-ریاضی-(سری13)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50012"
    } , 
    {
        id:50013,
        name:"نمونه سوال فصل 1-2-3 ریاضی",
        caption:"نمونه سوال فصل 1-2-3 ریاضی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-1-2-3-ریاضی-(سری8)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50013"
    } , 
    {
        id:50014,
        name:"نمونه سوال درس1-2-3 علوم تجربی",
        caption:"نمونه سوال درس1-2-3 علوم تجربی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس1-2-3-علوم-تجربی-(سری2)-پنجم-دبستان.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/oloom.jpg",
        slug: "/panjom/soalat/50014"
    } , 
    {
        id:50015,
        name:"نمونه سوال درس 1 تا 5 فارسی",
        caption:"نمونه سوال درس 1 تا 5 فارسی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-1-تا-5-فارسی-(سری3)-پنجم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/soalat/50015"
    } , 
    {
        id:50016,
        name:"آزمون املا درس 3 رازی و ساخت بیمارستان",
        caption:"آزمون املا درس 3 رازی و ساخت بیمارستان - فارسی پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/آزمون-املا-درس-3-رازی-و-ساخت-بیمارستان-فارسی-(سری3)-پنجم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/soalat/50016"
    } , 
    {
        id:50017,
        name:"آزمون مداد کاغذی درس 1-2-3-4 مطالعات اجتماعی",
        caption:"آزمون مداد کاغذی درس 1-2-3-4 مطالعات اجتماعی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"WORD",
        src:"/Files/panjom/soalat/آزمون-مداد-کاغذی-درس-1-2-3-4-مطالعات-اجتماعی-(سری1)-پنجم-دبستان.docx",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/soalat/50017"
    } , 
    {
        id:50018,
        name:"پرسش و پاسخ درس 3 هدیه های آسمانی",
        caption:"پرسش و پاسخ درس 3 هدیه های آسمانی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/پرسش-و-پاسخ-درس-3-........-هدیه-های-آسمانی-(سری1)-پنجم-دبستان.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/hedye.jpg",
        slug: "/panjom/soalat/50018"
    } , 
    {
        id:50019,
        name:"نمونه سوال درس 2 و 3 هدیه های آسمانی",
        caption:"نمونه سوال درس 2 و 3 هدیه های آسمانی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-2-و-3-هدیه-های-آسمانی-(سری3)-پنجم-دبستان.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/hedye.jpg",
        slug: "/panjom/soalat/50019"
    } ,
    {
        id:50020,
        name:"آزمون عملکردی درس 1-2-3-4 قرآن",
        caption:"آزمون عملکردی درس 1-2-3-4 قرآن - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/آزمون-عملکردی-درس-1-2-3-4-قرآن-(سری1)-پنجم-دبستان.pdf",
        book:"quran",
        boolInP:"قرآن",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/quran.jpg",
        slug: "/panjom/soalat/50020"
    } , 
    {
        id:50021,
        name:"نمونه سوال درس 1 تا 5 قرآن",
        caption:"نمونه سوال درس 1 تا 5 قرآن - پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-1-تا-5-قرآن-پنجم-ابتدایی.pdf",
        book:"quran",
        boolInP:"آموزش قرآن",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/quran.jpg",
        slug: "/panjom/soalat/50021"
    } , 
    {
        id:50022,
        name:"نمونه سوال فصل 2 درس 5 مطالعات اجتماعی ",
        caption:"نمونه سوال فصل 2 درس 5 مطالعات اجتماعی — پنجم ابتدایی",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-2-درس-5-مطالعات-اجتماعی-پنجم-ابتدایی.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/soalat/50022"
    } ,    {
        id:50023,
        name:"نمونه سوال علوم تجربی مهر ماه",
        caption:"نمونه سوال علوم تجربی مهر ماه — پنجم ابتدایی",
        creator:"خانم مریم سلطانی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"/Files/panjom/soalat/2015502080_352423422.pdf",
        book:"oloom",
        boolInP:"علوم",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/oloom.jpg",
        slug: "/panjom/soalat/50023"
    } ,    {
        id:50024,
        name:"نمونه سوال ارزیابی مطالعات اجتماعی مهر ماه",
        caption:"نمونه سوال ارزیابی مطالعات اجتماعی مهر ماه — پایه پنجم ابتدایی",
        creator:"خانم مریم سلطانی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"/Files/panjom/soalat/1849892609_1128582875_page-0002.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/soalat/50024"
    } ,    {
        id:50025,
        name:"نمونه سوال ارزیابی ریاضی مهرماه",
        caption:"نمونه سوال  ارزیابی ریاضی مهرماه — پنجم ابتدایی",
        creator:"خانم مریم سلطانی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"/Files/panjom/soalat/1814896387_-1867724943.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50025"
    } ,    {
        id:50026,
        name:"نمونه سوال ارزشیابی درس 3 و 4 و 5 هدیه های آسمان",
        caption:"نمونه سوال ارزشیابی درس 3 و 4 و 5 هدیه های آسمان — پنجم ابتدایی",
        creator:"سپهر ابراهیم پور",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"/Files/panjom/soalat/Hediyeh 3,4&5_053423.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/hedye.jpg",
        slug: "/panjom/soalat/50026"
    } ,    {
        id:50027,
        name:"نمونه سوال ارزشیابی درس 3 و 4 علوم",
        caption:"نمونه سوال نمونه سوال ارزشیابی درس 3 و 4 علوم — پنجم ابتدایی" ,
        creator:"سپهر ابراهیم پور",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"/Files/panjom/soalat/.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/oloom.jpg",
        slug: "/panjom/soalat/50027"
} ,    {
    id:50028,
    name:"سوالات هدیه های آسمان درس ۳ تا ۵",
    caption:"سوالات هدیه های آسمان درس ۳ تا ۵ - پایه پنجم" ,
    creator:"خانم ندا باقریان",
    upoledDate:"1403/09/09",
    fileType:"PDF",
    src:"https://coding-lbf.storage.iran.liara.space/%D9%87%D8%AF%DB%8C%D9%87%20%DB%B3%D8%AA%D8%A7%20%DB%B5.pdf",
    book:"hedye",
    boolInP:"هدیه های آسمان",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/hedye.jpg",
    slug: "/panjom/soalat/50028"
}
,    {
    id:50029,
    name:"ارزشیابی فصل اول ریاضی پنجم",
    caption:"ارزشیابی فصل اول ریاضی - پایه پنجم" ,
    creator:"خانم ندا باقریان",
    upoledDate:"1403/09/09",
    fileType:"WORD",
    src:"https://coding-lbf.storage.iran.liara.space/%40kelaspanj.docx",
    book:"riazi",
    boolInP:"ریاضی",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/riazi.jpg",
    slug: "/panjom/soalat/50029"
}
,    {
    id:50030,
    name:"نمونه سوالات فصل اول ریاضی - پایه پنجم",
    caption:"نمونه سوالات فصل اول ریاضی - پایه پنجم" ,
    creator:"خانم ندا باقریان",
    upoledDate:"1403/09/09",
    fileType:"PDF",
    src:"https://coding-lbf.storage.iran.liara.space/220_62693722838020.pdf",
    book:"riazi",
    boolInP:"ریاضی",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/riazi.jpg",
    slug: "/panjom/soalat/50030"
} ,    {
    id:50031,
    name:"نمونه سوال ریاضی، فصل 2",
    caption:"نمونه سوال ریاضی، فصل 2 - پایه پنجم" ,
    creator:"شایان حاجتی",
    upoledDate:"1403/09/29",
    fileType:"PDF",
    src:"https://coding-lbf.storage.iran.liara.space/panjom/hajati/01/%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%D8%8C%20%D9%81%D8%B5%D9%84%202.pdf",
    book:"riazi",
    boolInP:"ریاضی",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/riazi.jpg",
    slug: "/panjom/soalat/50031"
}
,    {
    id:50032,
    name:"نمونه سوال درس 3 تا 5 هدیه های آسمان",
    caption:"نمونه سوال درس 3 تا 5 هدیه های آسمان - پایه پنجم" ,
    creator:"خانم ندا باقریان",
    upoledDate:"1403/10/23",
    fileType:"PDF",
    src:"https://coding-lbf.storage.iran.liara.space/panjom/bagherian/04/%D9%87%D8%AF%DB%8C%D9%87%20%DB%B3%D8%AA%D8%A7%20%DB%B5.pdf",
    book:"hedye",
    boolInP:"هدیه های آسمان",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/hedye.jpg",
    slug: "/panjom/soalat/50032"
}
,    {
    id:50033,
    name:"نمونه سوال درس 3 تا 5 علوم تجربی",
    caption:"نمونه سوال درس 3 تا 5 علوم تجربی - پایه پنجم" ,
    creator:"خانم ندا باقریان",
    upoledDate:"1403/10/23",
    fileType:"PDF",
    src:"https://coding-lbf.storage.iran.liara.space/panjom/bagherian/04/%D8%B9%D9%84%D9%88%D9%85%20%DB%B3%20%D8%AA%D8%A7%20%DB%B5%20%D8%A8%D8%A7%D9%82%D8%B1%DB%8C%D8%A7%D9%86.pdf",
    book:"hedye",
    boolInP:"هدیه های آسمان",
    gradeInP:"پایه پنجم",
    image:"/images/components/modules/books/panjom/hedye.jpg",
    slug: "/panjom/soalat/50033"
},
     {
  "id": 66185,
  "name": "امتحان جبرانی ریاضی نوبت اول ( از فصل یک تا پایان فصل سوم",
  "caption": "امتحان جبرانی ریاضی نوبت اول ( از فصل یک تا پایان فصل سوم - پایه پنجم",
  "creator": "سپهر ابراهیم پور",
  "upoledDate": "1403/12/05",
  "fileType": "PDF",
  "src": "https://coding-lbf.storage.iran.liara.space/panjom/ebrahimpour/07/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%20%D8%AC%D8%A8%D8%B1%D8%A7%D9%86%DB%8C%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D9%86%D9%88%D8%A8%D8%AA%20%D8%A7%D9%88%D9%84%20%28%20%D8%A7%D8%B2%20%D9%81%D8%B5%D9%84%20%DB%8C%DA%A9%20%D8%AA%D8%A7%20%D9%BE%D8%A7%DB%8C%D8%A7%D9%86%20%D9%81%D8%B5%D9%84%20%D8%B3%D9%88%D9%85.pdf",
  "book": "riazi",
  "boolInP": "ریاضی",
  "gradeInP": "پایه پنجم",
  "category": "soalat",
  "image": "/images/components/modules/books/panjom/riazi.jpg",
  "slug": "/panjom/soalat/66185"
   },
    {
  "id": 89272,
  "name": "امتحان ریاضی دی ماه (از فصل یک تا پایان مبحث تقارن مرکزی درس ۴)",
  "caption": "امتحان ریاضی دی ماه (از فصل یک تا پایان مبحث تقارن مرکزی درس ۴) - پایه پنجم",
  "creator": "سپهر ابراهیم پور",
  "upoledDate": "1403/12/05",
  "fileType": "PDF",
  "src": "https://coding-lbf.storage.iran.liara.space/panjom/ebrahimpour/07/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D8%AF%DB%8C%20%D9%85%D8%A7%D9%87%20%28%D8%A7%D8%B2%20%D9%81%D8%B5%D9%84%20%DB%8C%DA%A9%20%D8%AA%D8%A7%20%D9%BE%D8%A7%DB%8C%D8%A7%D9%86%20%D9%85%D8%A8%D8%AD%D8%AB%20%D8%AA%D9%82%D8%A7%D8%B1%D9%86%20%D9%85%D8%B1%DA%A9%D8%B2%DB%8C%20%D8%AF%D8%B1%D8%B3%20%DB%B4%29.pdf",
  "book": "riazi",
  "boolInP": "ریاضی",
  "gradeInP": "پایه پنجم",
  "category": "soalat",
  "image": "/images/components/modules/books/panjom/riazi.jpg",
  "slug": "/panjom/soalat/89272"
},
    {
  "id": 83410,
  "name": "امتحان هدیه دی ماه ( از درس یک تا پایان درس ۷)",
  "caption": "امتحان هدیه دی ماه ( از درس یک تا پایان درس ۷) - پایه پنجم",
  "creator": "سپهر ابراهیم پور",
  "upoledDate": "1403/12/05",
  "fileType": "PDF",
  "src": "https://coding-lbf.storage.iran.liara.space/panjom/ebrahimpour/07/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%20%D9%87%D8%AF%DB%8C%D9%87%20%D8%AF%DB%8C%20%D9%85%D8%A7%D9%87%20%28%20%D8%A7%D8%B2%20%D8%AF%D8%B1%D8%B3%20%DB%8C%DA%A9%20%D8%AA%D8%A7%20%D9%BE%D8%A7%DB%8C%D8%A7%D9%86%20%D8%AF%D8%B1%D8%B3%20%DB%B7%29.pdf",
  "book": "hedye",
  "boolInP": "هدیه های آسمان",
  "gradeInP": "پایه پنجم",
  "category": "soalat",
  "image": "/images/components/modules/books/panjom/hedye.jpg",
  "slug": "/panjom/soalat/83410"
},
    
    

]

export default data
