import Head from "next/head";
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import Image from "next/image";
// import { Inter } from "next/font/google";
import HomePage from "@/components/templates/HomePage";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  
  return (
    <>
      <Head>
        <title>سامانه یادگیری مستمر دبستان شهید جهان آرا</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{minHeight:"100vh"}}>
        <HomePage />
      </main>
    </>
  );
}
